import { icon } from './icons.mjs';
// 피드백 컴포넌트 — Dialog · Toast · Empty state · Skeleton · Tooltip. 작성 규칙은 CONTRACT.md.
// 문자열은 홑따옴표 줄을 \n 으로 잇는다(template literal 금지).

export const css = [
  '  /* ── Dialog ── */',
  '  .dialog-stage{display:flex;align-items:center;justify-content:center;width:100%;padding:var(--dim-x8) var(--dim-x4);background:var(--bg-overlay);border-radius:var(--radius-md)}',
  '  .dialog{width:480px;max-width:100%;padding:var(--dim-x6);background:var(--bg-layer-floating);border-radius:var(--radius-lg);box-shadow:var(--shadow-3);text-align:left}',
  '  .dialog.sm{width:360px}',
  '  .dialog h4{margin:0 0 var(--dim-x2);font-size:var(--font-size-t4);line-height:var(--line-height-t4);font-weight:var(--font-weight-semibold);color:var(--fg-neutral)}',
  '  .dialog p{margin:0;font-size:var(--font-size-t2);line-height:var(--line-height-t2);color:var(--fg-neutral-subtle)}',
  '  .dialog-sum{margin-top:var(--dim-x4);padding:var(--dim-x3) var(--dim-x4);background:var(--bg-layer-basement);border-radius:var(--radius-md);font-size:var(--font-size-t2);line-height:var(--line-height-t2)}',
  '  .dialog-sum div{display:flex;justify-content:space-between;gap:var(--dim-x4);padding:var(--dim-x1) 0} .dialog-sum span{color:var(--fg-neutral-subtle)} .dialog-sum b{font-weight:var(--font-weight-semibold)}',
  '  .dialog-foot{display:flex;justify-content:flex-end;gap:var(--dim-x2);margin-top:var(--dim-x5)}',
  '  /* ── Toast ── */',
  '  .toast{display:inline-flex;align-items:center;gap:var(--dim-x3);min-width:280px;max-width:480px;padding:var(--dim-x3) var(--dim-x4);background:var(--bg-layer-floating);border-radius:var(--radius-lg);box-shadow:var(--shadow-3);font-size:var(--font-size-t2);line-height:var(--line-height-t2);color:var(--fg-neutral)}',
  '  .toast i{display:inline-flex;align-items:center;justify-content:center;flex:none;width:20px;height:20px;font-style:normal;color:var(--fg-neutral-subtle)} .toast i svg{width:18px;height:18px} .toast-x svg{width:14px;height:14px}',
  '  .toast.positive i{color:var(--fg-positive)} .toast.critical i{color:var(--fg-critical)} .toast.warning i{color:var(--fg-warning)}',
  '  .toast span{flex:1} .toast a{flex:none;font-weight:var(--font-weight-semibold);color:var(--fg-neutral);text-decoration:underline;text-underline-offset:2px}',
  '  .toast-x{display:inline-flex;align-items:center;justify-content:center;flex:none;width:20px;height:20px;border:0;padding:0;background:none;border-radius:var(--radius-xs);color:var(--fg-neutral-muted);font-size:var(--font-size-t3);line-height:normal;cursor:pointer} .toast-x:hover{background:var(--bg-neutral-hover)}',
  '  .toast-x:focus-visible{outline:none;box-shadow:0 0 0 3px var(--bg-accent-weak),0 0 0 4px var(--stroke-focus)}',
  '  .toast-stage{position:relative;width:100%;height:150px;border:1px dashed var(--stroke-neutral-stronger);border-radius:var(--radius-md);background:var(--bg-layer-default)}',
  '  .toast-stage .toast{position:absolute;left:50%;bottom:var(--dim-x4);transform:translateX(-50%)}',
  '  /* ── Empty state ── */',
  '  .empty{display:flex;flex-direction:column;align-items:center;text-align:center;width:100%;padding:var(--dim-x10) var(--dim-x6);gap:var(--dim-x1_5)}',
  '  .empty i{display:inline-flex;align-items:center;justify-content:center;width:48px;height:48px;margin:0 auto var(--dim-x2);border-radius:50%;font-style:normal;background:var(--bg-neutral-weak);color:var(--fg-neutral-subtle)} .empty i svg{width:24px;height:24px}',
  '  .empty.warning i{background:var(--bg-warning-weak);color:var(--fg-warning)} .empty.critical i{background:var(--bg-critical-weak);color:var(--fg-critical)}',
  '  .empty h4{margin:0;font-size:var(--font-size-t3);line-height:var(--line-height-t3);font-weight:var(--font-weight-semibold);color:var(--fg-neutral)}',
  '  .empty p{margin:0;max-width:320px;font-size:var(--font-size-t2);line-height:var(--line-height-t2);color:var(--fg-neutral-subtle)}',
  '  .empty .btn{margin-top:var(--dim-x3)}',
  '  .empty.compact{padding:var(--dim-x5) var(--dim-x4);gap:var(--dim-x1)} .empty.compact i{width:32px;height:32px;margin-bottom:var(--dim-x1);font-size:var(--font-size-t3)} .empty.compact h4{font-size:var(--font-size-t3);line-height:var(--line-height-t3)} .empty.compact .btn{margin-top:var(--dim-x2)}',
  '  /* ── Skeleton ── */',
  '  .skel{position:relative;display:block;overflow:hidden;background:var(--stroke-neutral-strong);border-radius:var(--radius-xs)}',
  '  .skel::after{content:"";position:absolute;inset:0;transform:translateX(-100%);background:linear-gradient(90deg,var(--bg-neutral-weak) 0%,var(--bg-layer-default) 50%,var(--bg-neutral-weak) 100%);opacity:.7;animation:skel-shimmer 1.4s var(--easing) infinite}',
  '  @keyframes skel-shimmer{to{transform:translateX(100%)}}',
  '  @media (prefers-reduced-motion:reduce){.skel::after{animation:none}}',
  '  .skel.text{height:14px;width:100%} .skel.line{height:8px;width:100%;border-radius:var(--radius-full)} .skel.circle{width:36px;height:36px;flex:none;border-radius:50%} .skel.card{height:120px;width:100%;border-radius:var(--radius-lg)}',
  '  .skel-qcard{display:flex;flex-direction:column;gap:var(--dim-x2_5);width:280px;padding:var(--dim-x4);background:var(--bg-layer-default);border:1px solid var(--stroke-neutral-strong);border-radius:var(--radius-lg)}',
  '  .skel-row{display:flex;align-items:center;gap:var(--dim-x2);width:100%}',
  '  /* ── Tooltip ── */',
  '  .tip-host{position:relative;display:inline-flex}',
  '  .tip{position:absolute;left:50%;bottom:calc(100% + var(--dim-x2));transform:translateX(-50%);padding:var(--dim-x1_5) var(--dim-x2);background:var(--bg-neutral-solid);color:var(--fg-on-neutral);font-size:12px;line-height:16px;font-weight:var(--font-weight-medium);border-radius:var(--radius-sm);white-space:nowrap;pointer-events:none;opacity:0;transition:opacity var(--duration-fast) var(--easing) 300ms}',
  '  .tip::after{content:"";position:absolute;left:50%;top:100%;margin-left:-4px;border:4px solid transparent;border-top-color:var(--bg-neutral-solid)}',
  '  .tip.bottom{bottom:auto;top:calc(100% + var(--dim-x2))} .tip.bottom::after{top:auto;bottom:100%;border-top-color:transparent;border-bottom-color:var(--bg-neutral-solid)}',
  '  .tip-host:hover>.tip,.tip-host:focus-within>.tip,.tip.on{opacity:1}',
].join('\n');

export const pages = [
  // ───────────── Dialog ─────────────
  '<section class="page" id="components/dialog">',
  '  <h1>Dialog</h1>',
  '  <p class="desc">에이전트가 실행하기 전에 무엇을 할지 확인받는 창입니다. 화면을 멈추고 답을 받아야 할 때만 씁니다.</p>',
  '  <h2>Anatomy</h2>',
  '  <div class="anatomy">',
  '    <div class="demo" style="padding:0;overflow:hidden"><div class="dialog-stage"><div class="dialog sm" role="dialog" aria-modal="true"><h4>연차를 신청할까요?</h4><p>아래 내용으로 연차 신청서를 올립니다. 상신 뒤에도 결재함에서 취소할 수 있습니다.</p><div class="dialog-sum"><div><span>항목</span><b>연차 신청</b></div><div><span>날짜</span><b>9/10 (수) · 1일</b></div><div><span>결재선</span><b>김부장 → 인사팀</b></div></div><div class="dialog-foot"><button class="btn md neutral-outline">취소</button><button class="btn md brand-solid">신청하기</button></div></div></div></div>',
  '    <ol><li><b>Title</b> — 질문형 한 줄(t4 Semibold)</li><li><b>Body</b> — 결과와 되돌리는 방법(t2 subtle)</li><li><b>Summary</b> (선택) — 에이전트가 실행할 값을 라벨·값 쌍으로</li><li><b>Footer</b> — 오른쪽 정렬, 취소(outline) + 주요 행동(solid) 하나</li></ol>',
  '  </div>',
  '  <h2>Properties</h2>',
  '  <h3>Size</h3>',
  '  <div class="demo" style="padding:0;overflow:hidden"><div class="dialog-stage" style="gap:var(--dim-x4);align-items:flex-start"><div class="dialog sm"><h4>퇴근을 기록할까요?</h4><p>18:02 기준으로 기록합니다.</p><div class="dialog-foot"><button class="btn md neutral-outline">취소</button><button class="btn md brand-solid">기록하기</button></div></div></div></div>',
  '  <table><tr><th>크기</th><th>폭</th><th>쓰임</th></tr><tr><td>sm</td><td>360px</td><td>한 줄 확인 — 출근·퇴근 기록, 대화 삭제</td></tr><tr><td>md</td><td>480px</td><td>기본 — 요약 상자가 있는 실행 전 확인</td></tr></table>',
  '  <h3>Variant</h3>',
  '  <div class="demo" style="padding:0;overflow:hidden"><div class="dialog-stage"><div class="dialog"><h4>상신을 취소할까요?</h4><p>「9월 지출결의」 결재 요청을 거둬들입니다. 결재선에 있는 사람에게 취소 알림이 갑니다.</p><div class="dialog-sum"><div><span>문서</span><b>9월 지출결의 · 184,000원</b></div><div><span>현재 상태</span><b>팀장 검토 중</b></div></div><div class="dialog-foot"><button class="btn md neutral-outline">돌아가기</button><button class="btn md critical-solid">상신 취소</button></div></div></div></div>',
  '  <table><tr><th>Variant</th><th>주요 버튼</th><th>쓰임</th></tr><tr><td>default</td><td>brand-solid</td><td>실행 전 확인 — 신청·기록·전송</td></tr><tr><td>destructive</td><td>critical-solid</td><td>되돌릴 수 없는 행동 — 상신 취소·삭제. 라벨에 행동을 그대로 적습니다</td></tr></table>',
  '  <h3>State</h3>',
  '  <div class="demo" style="padding:0;overflow:hidden"><div class="dialog-stage"><div class="dialog sm"><h4>연차를 신청할까요?</h4><p>신청서를 올리는 중입니다.</p><div class="dialog-foot"><button class="btn md neutral-outline" disabled>취소</button><button class="btn md brand-solid loading"><span class="spin"></span> 신청 중</button></div></div></div></div>',
  '  <p>실행 중에는 주요 버튼만 loading 으로 바꾸고 창은 유지합니다. 끝나면 창을 닫고 결과는 <a href="#components/toast">Toast</a> 로 알립니다.</p>',
  '  <h2>Guidelines</h2>',
  '  <div class="dd">',
  '    <div class="do"><b>Do</b><div class="demo" style="padding:0;overflow:hidden"><div class="dialog-stage" style="padding:var(--dim-x4)"><div class="dialog sm"><h4>연차를 신청할까요?</h4><div class="dialog-sum"><div><span>날짜</span><b>9/10 · 1일</b></div></div><div class="dialog-foot"><button class="btn sm neutral-outline">취소</button><button class="btn sm brand-solid">신청하기</button></div></div></div></div>제목은 질문, 요약 상자엔 실제 값, 주요 버튼은 행동 그대로.</div>',
  '    <div class="dont"><b>Don&#39;t</b><div class="demo" style="padding:0;overflow:hidden"><div class="dialog-stage" style="padding:var(--dim-x4)"><div class="dialog sm"><h4>알림</h4><p>계속하시겠습니까?</p><div class="dialog-foot"><button class="btn sm brand-solid">아니오</button><button class="btn sm brand-solid">예</button></div></div></div></div>무엇을 하는지 모르는 제목·「예/아니오」, solid 두 개.</div>',
  '  </div>',
  '  <div class="dd">',
  '    <div class="do"><b>Do</b>닫는 길 셋을 모두 엽니다 — <b>ESC</b>·배경 클릭·취소 버튼은 같은 「취소」. 열리면 포커스는 창 안 첫 버튼(취소)으로 가고 <b>Tab</b> 은 창 안에서만 순환합니다.</div>',
  '    <div class="dont"><b>Don&#39;t</b>정보만 보여 주려고 Dialog 를 열지 않습니다(Notice·Toast 로). Dialog 위에 Dialog 를 겹치지 않습니다.</div>',
  '  </div>',
  '  <h2>Dialog vs. Bottom sheet(모바일)</h2>',
  '  <table><tr><th></th><th>Dialog</th><th>Bottom sheet</th></tr><tr><td>위치</td><td>화면 중앙, 폭 고정(360/480)</td><td>하단, 화면 폭 전체</td></tr><tr><td>내용</td><td>확인 한 번 — 질문 + 요약 + 버튼 둘</td><td>선택지 여러 개·긴 내용, 안에서 스크롤</td></tr><tr><td>닫기</td><td>ESC · 배경 클릭 · 취소</td><td>아래로 끌기 · 배경 탭</td></tr><tr><td>모바일</td><td>sm 만, 폭 = 화면 - 32px</td><td>기본</td></tr></table>',
  '  <h2>Specification</h2>',
  '  <table><tr><th>부위</th><th>토큰</th></tr>',
  '    <tr><td>Overlay</td><td><code>--bg-overlay</code></td></tr>',
  '    <tr><td>Container</td><td><code>--bg-layer-floating</code> · <code>--radius-lg</code> · <code>--shadow-3</code> · 패딩 <code>--dim-x6</code> · 폭 sm 360 / md 480</td></tr>',
  '    <tr><td>Title</td><td>t4 <code>--font-weight-semibold</code> <code>--fg-neutral</code></td></tr>',
  '    <tr><td>Body</td><td>t2 <code>--fg-neutral-subtle</code></td></tr>',
  '    <tr><td>Summary</td><td><code>--bg-layer-basement</code> · <code>--radius-md</code> · 패딩 <code>--dim-x3</code> <code>--dim-x4</code> · 라벨 <code>--fg-neutral-subtle</code> / 값 Semibold</td></tr>',
  '    <tr><td>Footer</td><td>오른쪽 정렬 · 간격 <code>--dim-x2</code> · 위 여백 <code>--dim-x5</code> · Button md</td></tr>',
  '    <tr><td>접근성</td><td><code>role="dialog" aria-modal="true" aria-labelledby=제목</code> · 포커스 트랩 · ESC = 취소</td></tr></table>',
  '</section>',
  // ───────────── Toast ─────────────
  '<section class="page" id="components/toast">',
  '  <h1>Toast</h1>',
  '  <p class="desc">방금 한 행동의 결과를 짧게 알리고 사라지는 떠 있는 알림입니다. 사용자가 시작한 작업의 결과에만 씁니다.</p>',
  '  <h2>Anatomy</h2>',
  '  <div class="anatomy">',
  '    <div class="demo"><div class="toast positive" role="status"><i>' + icon('circle-check-filled') + '</i><span>연차 신청서를 올렸습니다</span><a href="#components/toast">되돌리기</a><button class="toast-x" aria-label="닫기">' + icon('x') + '</button></div></div>',
  '    <ol><li><b>Icon</b> — filled 18px, 상태색. 뒤 배경 없음</li><li><b>Message</b> — 한 줄, 무엇이 됐는지</li><li><b>Action</b> (선택) — 링크 하나(되돌리기·보기)</li><li><b>Close</b> — sticky 일 때 필수</li></ol>',
  '  </div>',
  '  <h2>Properties</h2>',
  '  <h3>Variant</h3>',
  '  <div class="demo col" style="align-items:flex-start">',
  '    <div class="toast"><i>' + icon('info-circle-filled') + '</i><span>업무일지 초안을 만드는 중입니다</span></div>',
  '    <div class="toast positive"><i>' + icon('circle-check-filled') + '</i><span>퇴근 18:02 로 기록했습니다</span><a href="#components/toast">되돌리기</a></div>',
  '    <div class="toast critical"><i>' + icon('alert-circle-filled') + '</i><span>결재 승인에 실패했습니다 — 세션이 만료됐습니다</span><a href="#components/toast">다시 시도</a><button class="toast-x" aria-label="닫기">' + icon('x') + '</button></div>',
  '    <div class="toast warning"><i>' + icon('alert-triangle-filled') + '</i><span>근태 시스템 응답이 느립니다. 기록은 저장됐습니다</span></div>',
  '  </div>',
  '  <table><tr><th>Variant</th><th>쓰임</th></tr><tr><td>neutral</td><td>진행·안내 — 초안 생성 중, 복사됨</td></tr><tr><td>positive</td><td>완료 — 신청·기록·승인 성공</td></tr><tr><td>critical</td><td>실패 — 원인 + 다시 시도, 스스로 사라지지 않습니다</td></tr><tr><td>warning</td><td>됐지만 주의 — 부분 성공, 지연</td></tr></table>',
  '  <h3>Duration</h3>',
  '  <table><tr><th>상황</th><th>지속</th><th>닫기 버튼</th></tr><tr><td>neutral · positive · warning</td><td>4초</td><td>없음</td></tr><tr><td>action 이 있을 때</td><td>8초(되돌릴 시간)</td><td>없음</td></tr><tr><td>critical</td><td>sticky — 사용자가 닫을 때까지</td><td>필수</td></tr></table>',
  '  <h3>Position</h3>',
  '  <div class="demo" style="padding:0"><div class="toast-stage"><div class="toast positive"><i>' + icon('circle-check-filled') + '</i><span>회의실 A 를 14:00 에 예약했습니다</span><a href="#components/toast">보기</a></div></div></div>',
  '  <p>화면 아래 가운데, 바닥에서 <code>--dim-x4</code>. 컴포저가 있는 대화 화면에서는 컴포저 위에 뜹니다. 여러 개가 쌓이면 최신이 아래, 최대 3개.</p>',
  '  <h2>Guidelines</h2>',
  '  <div class="dd">',
  '    <div class="do"><b>Do</b><div class="demo"><div class="toast positive"><i>' + icon('circle-check-filled') + '</i><span>대화를 삭제했습니다</span><a href="#components/toast">되돌리기</a></div></div>되돌릴 수 있는 행동엔 「되돌리기」를 붙이고 8초를 줍니다.</div>',
  '    <div class="dont"><b>Don&#39;t</b><div class="demo"><div class="toast"><i>' + icon('info-circle-filled') + '</i><span>삭제하시겠습니까?</span><a href="#components/toast">삭제</a><a href="#components/toast">취소</a></div></div>토스트로 묻지 않습니다 — 답을 받아야 하면 <a href="#components/dialog">Dialog</a>.</div>',
  '  </div>',
  '  <div class="dd">',
  '    <div class="do"><b>Do</b>한 줄, 결과 중심으로: <b>퇴근 18:02 로 기록했습니다</b>. 실패는 원인을 한 구절로.</div>',
  '    <div class="dont"><b>Don&#39;t</b>사용자가 시작하지 않은 시스템 소식(정기 동기화 완료 등)을 토스트로 띄우지 않습니다. 화면에 남아야 할 정보도 안 됩니다.</div>',
  '  </div>',
  '  <h2>Toast vs. Notice(inline)</h2>',
  '  <table><tr><th></th><th>Toast</th><th>Notice</th></tr><tr><td>위치</td><td>화면 위에 떠서, 하단 가운데</td><td>내용 흐름 안, 관련 요소 바로 옆</td></tr><tr><td>지속</td><td>4초 뒤 사라짐(오류는 sticky)</td><td>상태가 풀릴 때까지 남음</td></tr><tr><td>내용</td><td>방금 한 행동의 결과</td><td>지금 화면의 상태·조건(연동 안 됨, 결재 대기)</td></tr><tr><td>행동</td><td>링크 하나까지</td><td>버튼 가능</td></tr></table>',
  '  <h2>Specification</h2>',
  '  <table><tr><th>부위</th><th>토큰</th></tr>',
  '    <tr><td>Container</td><td><code>--bg-layer-floating</code> · <code>--radius-lg</code> · <code>--shadow-3</code> · 패딩 <code>--dim-x3</code> <code>--dim-x4</code> · 폭 280–480</td></tr>',
  '    <tr><td>Message</td><td>t2 <code>--fg-neutral</code></td></tr>',
  '    <tr><td>Icon</td><td>18px filled · neutral <code>--fg-neutral-subtle</code> · positive <code>--fg-positive</code> · critical <code>--fg-critical</code> · warning <code>--fg-warning</code></td></tr>',
  '    <tr><td>Action</td><td>t2 <code>--font-weight-semibold</code> <code>--fg-neutral</code> 밑줄</td></tr>',
  '    <tr><td>Close</td><td>20px · <code>--fg-neutral-muted</code> · hover <code>--bg-neutral-hover</code></td></tr>',
  '    <tr><td>접근성</td><td><code>role="status"</code>(critical 은 <code>role="alert"</code>) · 닫기 버튼 <code>aria-label="닫기"</code> · 마우스 올리면 타이머 정지</td></tr></table>',
  '</section>',
  // ───────────── Empty state ─────────────
  '<section class="page" id="components/empty-state">',
  '  <h1>Empty state</h1>',
  '  <p class="desc">보여 줄 내용이 없을 때 그 자리를 채우는 안내입니다. 왜 비었는지와 다음에 할 일을 알려 줍니다.</p>',
  '  <h2>Anatomy</h2>',
  '  <div class="anatomy">',
  '    <div class="demo"><div class="empty"><i>' + icon('sparkles') + '</i><h4>아직 대화가 없습니다</h4><p>연차·결재·출퇴근처럼 하고 싶은 일을 말해 보세요.</p><button class="btn md brand-solid">새 대화</button></div></div>',
  '    <ol><li><b>Icon</b> — 48px 원, <code>--bg-neutral-weak</code></li><li><b>Title</b> — 상황 한 줄(t3 Semibold)</li><li><b>Description</b> — 이유 또는 힌트(t2 subtle, 320px 안)</li><li><b>CTA</b> (선택) — 다음 행동 하나</li></ol>',
  '  </div>',
  '  <h2>Properties</h2>',
  '  <h3>Variant</h3>',
  '  <div class="demo" style="display:grid;grid-template-columns:1fr 1fr;align-items:stretch">',
  '    <div style="background:var(--bg-layer-default);border-radius:var(--radius-md)"><div class="empty"><i>' + icon('sparkles') + '</i><h4>아직 대화가 없습니다</h4><p>연차·결재·출퇴근처럼 하고 싶은 일을 말해 보세요.</p><button class="btn md brand-solid">새 대화</button></div></div>',
  '    <div style="background:var(--bg-layer-default);border-radius:var(--radius-md)"><div class="empty"><i>' + icon('search') + '</i><h4>「지출결의」 결과가 없습니다</h4><p>담당자 이름이나 시스템 이름으로 다시 검색해 보세요.</p><button class="btn md neutral-outline">검색어 지우기</button></div></div>',
  '    <div style="background:var(--bg-layer-default);border-radius:var(--radius-md)"><div class="empty warning"><i>' + icon('alert-triangle') + '</i><h4>근태 시스템이 연동되지 않았습니다</h4><p>연결하면 출퇴근 기록과 이번 주 현황을 여기서 바로 봅니다.</p><button class="btn md brand-solid">연동하기</button></div></div>',
  '    <div style="background:var(--bg-layer-default);border-radius:var(--radius-md)"><div class="empty critical"><i>' + icon('alert-circle') + '</i><h4>결재함을 불러오지 못했습니다</h4><p>전자결재 서버가 응답하지 않습니다. 잠시 뒤 다시 시도해 주세요.</p><button class="btn md neutral-outline">다시 시도</button></div></div>',
  '  </div>',
  '  <table><tr><th>Variant</th><th>아이콘 칩</th><th>CTA</th><th>쓰임</th></tr><tr><td>첫 사용</td><td>neutral · sparkles</td><td>brand-solid</td><td>대화·업무일지·일정이 하나도 없을 때 — 시작을 권합니다</td></tr><tr><td>결과 없음</td><td>neutral · search-off</td><td>neutral-outline</td><td>검색·필터 결과가 비었을 때 — 조건을 바꾸게 합니다</td></tr><tr><td>연동 안 됨</td><td>warning</td><td>brand-solid</td><td>사내 시스템 미연결 — 연동하면 무엇이 되는지 적습니다</td></tr><tr><td>오류</td><td>critical</td><td>neutral-outline 「다시 시도」</td><td>불러오기 실패 — 원인 한 줄</td></tr></table>',
  '  <h3>Size</h3>',
  '  <div class="demo"><div class="card" style="width:300px;padding:0"><div class="empty compact"><i>' + icon('search') + '</i><h4>대기 중인 결재가 없습니다</h4><p>새 결재가 오면 여기에 보입니다.</p></div></div><div class="card" style="width:300px;padding:0"><div class="empty compact critical"><i>' + icon('alert-circle') + '</i><h4>불러오지 못했습니다</h4><button class="btn sm neutral-outline">다시 시도</button></div></div></div>',
  '  <table><tr><th>크기</th><th>아이콘</th><th>제목</th><th>쓰임</th></tr><tr><td>default</td><td>48px</td><td>t3</td><td>화면·탭 전체가 비었을 때</td></tr><tr><td>compact</td><td>32px</td><td>t3</td><td>카드·패널 안(빠른 실행 카드, 내 현황)</td></tr></table>',
  '  <h2>Guidelines</h2>',
  '  <div class="dd">',
  '    <div class="do"><b>Do</b><div class="demo"><div class="empty compact"><i>' + icon('sparkles') + '</i><h4>이번 주 업무일지가 없습니다</h4><p>연동 소스로 초안을 자동 작성합니다.</p><button class="btn sm brand-solid">오늘 일지 쓰기</button></div></div>비었으니 무엇을 하면 되는지 — 다음 행동을 CTA 로 줍니다.</div>',
  '    <div class="dont"><b>Don&#39;t</b><div class="demo"><div class="empty compact"><i>' + icon('inbox') + '</i><h4>데이터가 없습니다</h4></div></div>「데이터 없음」「No data」처럼 상태만 적고 끝내지 않습니다.</div>',
  '  </div>',
  '  <div class="dd">',
  '    <div class="do"><b>Do</b>오류엔 원인 한 줄 + 「다시 시도」. 연동 안 됨엔 연동하면 얻는 것을 적습니다.</div>',
  '    <div class="dont"><b>Don&#39;t</b>큰 일러스트·긴 설명으로 채우지 않습니다. 결과 없음에 brand-solid 를 쓰지 않습니다 — 주요 행동이 아닙니다.</div>',
  '  </div>',
  '  <h2>Empty state vs. Skeleton</h2>',
  '  <table><tr><th></th><th>Empty state</th><th>Skeleton</th></tr><tr><td>뜻</td><td>불러왔는데 내용이 없다</td><td>아직 불러오는 중이다</td></tr><tr><td>시점</td><td>응답이 온 뒤</td><td>응답이 오기 전 1–3초</td></tr><tr><td>행동</td><td>CTA 있음</td><td>없음</td></tr></table>',
  '  <h2>Specification</h2>',
  '  <table><tr><th>부위</th><th>토큰</th></tr>',
  '    <tr><td>Container</td><td>세로 가운데 정렬 · 패딩 <code>--dim-x10</code> <code>--dim-x6</code>(compact <code>--dim-x5</code> <code>--dim-x4</code>) · 간격 <code>--dim-x1_5</code></td></tr>',
  '    <tr><td>Icon</td><td>48px 원(compact 32) · <code>--bg-neutral-weak</code>/<code>--fg-neutral-subtle</code> · warning <code>--bg-warning-weak</code>/<code>--fg-warning</code> · critical <code>--bg-critical-weak</code>/<code>--fg-critical</code></td></tr>',
  '    <tr><td>Title</td><td>t3 <code>--font-weight-semibold</code>(compact t3)</td></tr>',
  '    <tr><td>Description</td><td>t2 <code>--fg-neutral-subtle</code> · 최대 320px</td></tr>',
  '    <tr><td>CTA</td><td>Button md(compact sm) · 위 여백 <code>--dim-x3</code></td></tr>',
  '    <tr><td>접근성</td><td>아이콘은 장식(<code>aria-hidden</code>) · 제목이 그 영역의 이름이 되게 <code>h2</code>–<code>h4</code> 수준으로</td></tr></table>',
  '</section>',
  // ───────────── Skeleton ─────────────
  '<section class="page" id="components/skeleton">',
  '  <h1>Skeleton</h1>',
  '  <p class="desc">내용이 오기 전에 화면 구조를 먼저 그려 두는 회색 자리표시입니다. 1–3초 구간의 첫 로딩에만 씁니다.</p>',
  '  <h2>Anatomy</h2>',
  '  <div class="anatomy">',
  '    <div class="demo"><div class="skel-qcard"><div class="skel-row"><span class="skel circle"></span><span class="skel text" style="width:120px"></span></div><span class="skel text"></span><span class="skel text" style="width:70%"></span><div class="skel-row" style="margin-top:var(--dim-x1)"><span class="skel card" style="width:64px;height:32px;border-radius:var(--radius-md)"></span><span class="skel card" style="width:64px;height:32px;border-radius:var(--radius-md)"></span></div></div></div>',
  '    <ol><li><b>Block</b> — <code>--stroke-neutral-strong</code> 바탕의 자리표시, 실제 요소와 같은 크기</li><li><b>Shimmer</b> — 왼쪽에서 오른쪽으로 한 번씩 지나가는 밝은 띠(1.4초)</li><li><b>Layout</b> — 실제 컴포넌트와 같은 컨테이너·간격</li></ol>',
  '  </div>',
  '  <h2>Properties</h2>',
  '  <h3>Shape</h3>',
  '  <div class="demo col" style="max-width:420px"><span class="skel text"></span><span class="skel line"></span><span class="skel circle"></span><span class="skel card"></span></div>',
  '  <table><tr><th>Shape</th><th>크기</th><th>흉내내는 것</th></tr><tr><td>text</td><td>높이 14px · 폭 부모 또는 지정</td><td>본문·제목 한 줄(마지막 줄은 60–80%)</td></tr><tr><td>line</td><td>높이 8px · 알약</td><td>캡션·라벨</td></tr><tr><td>circle</td><td>36px</td><td>아이콘 칩·아바타</td></tr><tr><td>card</td><td>높이 120px · radius-lg</td><td>이미지·차트·버튼(크기 지정)</td></tr></table>',
  '  <h3>Composition</h3>',
  '  <div class="demo"><div class="skel-qcard"><div class="skel-row"><span class="skel circle"></span><span class="skel text" style="width:96px"></span></div><span class="skel text" style="width:85%"></span><div class="skel-row" style="margin-top:var(--dim-x1)"><span class="skel card" style="width:56px;height:32px;border-radius:var(--radius-md)"></span><span class="skel card" style="width:56px;height:32px;border-radius:var(--radius-md)"></span></div></div><div class="skel-qcard"><div class="skel-row"><span class="skel circle"></span><span class="skel text" style="width:72px"></span></div><span class="skel text" style="width:60%"></span><div class="skel-row" style="margin-top:var(--dim-x1)"><span class="skel card" style="width:56px;height:32px;border-radius:var(--radius-md)"></span></div></div></div>',
  '  <p>빠른 실행 카드 스켈레톤 — 아이콘 칩 36px · 제목 한 줄 · 설명 한 줄 · 하단 sm 버튼 자리. 실제 카드와 컨테이너(라운드 lg · 선 strong · 패딩)를 같이 씁니다.</p>',
  '  <h2>Guidelines</h2>',
  '  <div class="dd">',
  '    <div class="do"><b>Do</b><div class="demo"><div class="skel-qcard" style="width:220px"><div class="skel-row"><span class="skel circle"></span><span class="skel text" style="width:80px"></span></div><span class="skel text"></span><span class="skel text" style="width:65%"></span></div></div>구조를 흉내냅니다 — 줄 수·아이콘 자리·폭이 실제 내용과 같게.</div>',
  '    <div class="dont"><b>Don&#39;t</b><div class="demo"><span class="skel card" style="width:220px;height:96px"></span></div>큰 회색 상자 하나로 덮지 않습니다. 실제와 달라 내용이 오면 화면이 튑니다.</div>',
  '  </div>',
  '  <div class="dd">',
  '    <div class="do"><b>Do</b>1–3초 구간에만. 0.3초 안에 오면 아무것도 보이지 않고, 3초를 넘기면 「불러오는 중」 문구, 10초를 넘기면 정형 Progress + 취소(<a href="#foundations/state">Loading</a>).</div>',
  '    <div class="dont"><b>Don&#39;t</b>새로고침·더 불러오기에 스켈레톤을 쓰지 않습니다 — 기존 내용은 유지하고 Progress circle 을 씁니다. 스켈레톤 위에 글자를 얹지 않습니다.</div>',
  '  </div>',
  '  <h2>Skeleton vs. Progress circle</h2>',
  '  <table><tr><th></th><th>Skeleton</th><th>Progress circle</th></tr><tr><td>알려주는 것</td><td>무엇이 올지(구조)</td><td>진행 중이라는 사실</td></tr><tr><td>언제</td><td>첫 진입, 리스트·카드 1–3초</td><td>버튼 안, 새로고침, 더 불러오기</td></tr><tr><td>내용 교체</td><td>같은 자리에 그대로</td><td>원이 사라지고 내용 추가</td></tr></table>',
  '  <h2>Specification</h2>',
  '  <table><tr><th>부위</th><th>토큰</th></tr>',
  '    <tr><td>Block</td><td><code>--stroke-neutral-strong</code> · <code>--radius-xs</code>(line <code>--radius-full</code>, card <code>--radius-lg</code>)</td></tr>',
  '    <tr><td>Shimmer</td><td><code>--bg-neutral-weak</code> → <code>--bg-layer-default</code> → <code>--bg-neutral-weak</code> 90° 그라디언트 · 1.4초 <code>--easing</code> 반복</td></tr>',
  '    <tr><td>Composition</td><td>실제 컴포넌트의 컨테이너 토큰 그대로 — 카드 <code>--radius-lg</code> <code>--stroke-neutral-strong</code> 패딩 <code>--dim-x4</code></td></tr>',
  '    <tr><td>접근성</td><td>컨테이너에 <code>aria-busy="true"</code> · 블록은 <code>aria-hidden</code> · <code>prefers-reduced-motion</code> 이면 shimmer 정지</td></tr></table>',
  '</section>',
  // ───────────── Tooltip ─────────────
  '<section class="page" id="components/tooltip">',
  '  <h1>Tooltip</h1>',
  '  <p class="desc">아이콘 버튼처럼 라벨이 없는 요소에 마우스를 올리거나 포커스하면 이름을 보여 주는 짧은 말풍선입니다.</p>',
  '  <h2>Anatomy</h2>',
  '  <div class="anatomy">',
  '    <div class="demo" style="padding-top:56px"><span class="tip-host"><button class="iconbtn md outline" aria-label="첨부">' + icon('paperclip') + '</button><span class="tip on" role="tooltip">파일 첨부</span></span></div>',
  '    <ol><li><b>Container</b> — 잉크 배경, 12px Medium, radius-sm</li><li><b>Arrow</b> — 4px, 트리거 가운데를 가리킵니다</li><li><b>Trigger</b> — 아이콘 버튼·잘린 글자·상태 점</li></ol>',
  '  </div>',
  '  <h2>Properties</h2>',
  '  <h3>Position</h3>',
  '  <div class="demo" style="padding:56px var(--dim-x6);gap:var(--dim-x8)"><span class="tip-host"><button class="iconbtn md outline" aria-label="계획 세우기">' + icon('menu-2') + '</button><span class="tip on" role="tooltip">계획 세우기</span></span><span class="tip-host"><button class="iconbtn md outline" aria-label="새 대화">' + icon('plus') + '</button><span class="tip bottom on" role="tooltip">새 대화</span></span></div>',
  '  <table><tr><th>위치</th><th>쓰임</th></tr><tr><td>top</td><td>기본 — 컴포저·본문 안 아이콘 버튼</td></tr><tr><td>bottom</td><td>상단 바·사이드바 위쪽처럼 위에 공간이 없을 때</td></tr></table>',
  '  <h3>State</h3>',
  '  <div class="demo" style="padding-top:56px;gap:var(--dim-x8)"><span class="tip-host"><button class="iconbtn md outline" aria-label="첨부">' + icon('paperclip') + '</button><span class="tip" role="tooltip">파일 첨부</span></span><span class="tip-host"><button class="iconbtn md outline" aria-label="첨부">' + icon('paperclip') + '</button><span class="tip on" role="tooltip">파일 첨부</span></span></div>',
  '  <p>숨김(기본) → 마우스 올림·포커스 300ms 뒤 표시 → 벗어나면 즉시 숨김. 왼쪽 버튼에 마우스를 올려 보세요.</p>',
  '  <h2>Guidelines</h2>',
  '  <div class="dd">',
  '    <div class="do"><b>Do</b><div class="demo" style="padding-top:48px"><span class="tip-host"><button class="iconbtn md outline" aria-label="첨부">' + icon('paperclip') + '</button><span class="tip on">파일 첨부</span></span></div>라벨 없는 아이콘 버튼엔 필수. 내용은 <code>aria-label</code> 과 같은 이름.</div>',
  '    <div class="dont"><b>Don&#39;t</b><div class="demo" style="padding-top:48px"><span class="tip-host"><button class="btn sm brand-solid">신청하기</button><span class="tip on">잔여 연차 3일 · 결재선 김부장</span></span></div>꼭 알아야 할 정보를 툴팁에만 두지 않습니다 — 터치에선 볼 수 없습니다.</div>',
  '  </div>',
  '  <div class="dd">',
  '    <div class="do"><b>Do</b>한두 단어. 300ms 지연으로 스쳐 지나갈 때 깜빡이지 않게 합니다.</div>',
  '    <div class="dont"><b>Don&#39;t</b>링크·버튼·여러 줄을 넣지 않습니다 — 그건 Popover. 이미 라벨이 보이는 버튼에 같은 말을 반복하지 않습니다.</div>',
  '  </div>',
  '  <h2>Tooltip vs. Popover</h2>',
  '  <table><tr><th></th><th>Tooltip</th><th>Popover</th></tr><tr><td>내용</td><td>이름 한두 단어</td><td>설명·행동·폼</td></tr><tr><td>열기</td><td>hover·focus, 300ms 지연</td><td>클릭·탭</td></tr><tr><td>닫기</td><td>벗어나면 자동</td><td>바깥 클릭·ESC·닫기 버튼</td></tr><tr><td>포커스</td><td>안 옮김</td><td>안으로 옮김</td></tr><tr><td>모양</td><td>잉크 배경 · 흰 글자 · radius-sm</td><td>흰 배경 · shadow-2 · radius-lg</td></tr></table>',
  '  <h2>Specification</h2>',
  '  <table><tr><th>부위</th><th>토큰</th></tr>',
  '    <tr><td>Container</td><td><code>--bg-neutral-solid</code> · <code>--fg-on-neutral</code> · 12px <code>--font-weight-medium</code> · 패딩 <code>--dim-x1_5</code> <code>--dim-x2</code> · <code>--radius-sm</code></td></tr>',
  '    <tr><td>Arrow</td><td>4px 삼각형 · <code>--bg-neutral-solid</code></td></tr>',
  '    <tr><td>Offset</td><td>트리거에서 <code>--dim-x2</code></td></tr>',
  '    <tr><td>Motion</td><td>표시 지연 300ms · 페이드 <code>--duration-fast</code> <code>--easing</code></td></tr>',
  '    <tr><td>접근성</td><td><code>role="tooltip"</code> · 트리거에 <code>aria-describedby</code>(라벨을 대신하면 <code>aria-label</code>) · 키보드 포커스에도 표시 · ESC 로 닫힘</td></tr></table>',
  '</section>',
].join('\n');

export const nav = [
  ['components/dialog', 'Dialog'],
  ['components/toast', 'Toast'],
  ['components/empty-state', 'Empty state'],
  ['components/skeleton', 'Skeleton'],
  ['components/tooltip', 'Tooltip'],
];
